### ISSUE TITLE
Attribute based rate limit rules?

### ISSUE THREAD

**Issue by DanFTRX** [stefanprodan/AspNetCoreRateLimit#140] opened 2020-08-21 15:11 UTC
It would be convenient for readability to be able to define rate limit rules in an attribute on the routes themselves.

**Comment by cristipufu** [comment] 2020-09-26 17:54
Duplicate of: https://github.com/stefanprodan/AspNetCoreRateLimit/issues/19

**Closed** 2020-09-26 17:54 UTC
Labels: duplicate
