### ISSUE TITLE
wildcard character for Endpoint value

### ISSUE THREAD

**Issue by jcyuan** [stefanprodan/AspNetCoreRateLimit#91] opened 2019-08-23 07:21 UTC
`/api/v{version}/shp/buy`

my api has version controlling, so how should I define the limiting in the appsettings?

`get:/api/v*/shp/buy`    seems not work.

**Comment by liguobao** [comment] 2019-09-02 08:17
me too...

**Comment by corcus** [comment] 2020-03-03 15:05
Wildcards for endpoints would be really useful in general.
For example get:/api/something/* to cover every get action in the "something" controller would be a good feature.

**Comment by TabaKhan** [comment] 2020-04-23 10:36
_/api/*/something_ would be a replacement for _/api/v{version:apiVersion}/something_ but the problem is that the counter is separated. When /api/v1.0/something reaches the limit _/api/v1.00/something_ is still free to be called.

**Comment by cristipufu** [comment] 2020-04-23 11:55
One can create and configure his own counter: https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/CounterKeyBuilders/EndpointCounterKeyBuilder.cs

**Comment by cristipufu** [comment] 2020-10-31 19:19
This can be fixed by switching the default `EndpointCounterKeyBuilder` implementation from a `PathCounterKeyBuilder` instance to a`EndpointCounterKeyBuilder` instance.

**Closed by cristipufu** 2020-10-31 19:19 UTC
